pipeline {
    agent any

    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'v1', description: 'Image tag')
    }

    environment {
        DOCKER_USER = "rajeevreddy1511"
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',url: 'https://github.com/Rajeev151124/hmis-project-1.git'
            }
        }

        stage('Update YAML') {
            steps {
                sh '''
                sed -i "s|patient-service-1:.*|patient-service-1:${IMAGE_TAG}|" k8s/patient-deploy.yaml
                sed -i "s|visit-service-1:.*|visit-service-1:${IMAGE_TAG}|" k8s/visit-deploy.yaml
                sed -i "s|frontend-service-1:.*|frontend-service-1:${IMAGE_TAG}|" k8s/frontend-deploy.yaml
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}
